# Generated by Django 4.1.1 on 2023-03-23 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentcenter',
            name='doctor_photo',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='treatment_center/'),
        ),
    ]
