# Generated by Django 4.1.1 on 2023-03-23 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treatment_center', '0002_alter_treatmentcenter_doctor_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentcenter',
            name='factor',
        ),
        migrations.CreateModel(
            name='SelectMutipleFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment_center.factor', verbose_name='Factor')),
                ('treatment_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment_center.treatmentcenter')),
            ],
            options={
                'verbose_name_plural': 'Select Factor',
            },
        ),
    ]
