# Generated by Django 4.1.1 on 2023-03-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment_center', '0003_remove_treatmentcenter_factor_selectmutiplefactor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatmentcenter',
            old_name='doctor_photo',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='treatmentcenter',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentcenter',
            name='room_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
