# Generated by Django 4.1.1 on 2023-03-25 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment_center', '0004_rename_doctor_photo_treatmentcenter_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treatmentcity',
            options={'verbose_name_plural': 'City'},
        ),
        migrations.AlterField(
            model_name='factor',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Available'), (0, 'Not Available')], default=1),
        ),
        migrations.AlterField(
            model_name='treatmentcity',
            name='city_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='treatmentcity',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Available'), (0, 'Not Available')], default=1),
        ),
    ]
