# Generated by Django 4.1.1 on 2023-03-25 06:29

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatment_center', '0006_treatmentcenter_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentcity',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='city_name', unique=True),
        ),
    ]
