# Generated by Django 4.1.1 on 2023-04-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment_center', '0009_uploadmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmap',
            name='image',
            field=models.ImageField(upload_to='hemophilia/'),
        ),
    ]
