# Generated by Django 4.1.1 on 2023-03-07 17:12

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='activity_post/')),
                ('post_by', models.CharField(default='admin', max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sub_title', models.CharField(blank=True, max_length=400, null=True)),
                ('pr_image', models.ImageField(blank=True, null=True, upload_to='post_image/')),
                ('english_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('hindi_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('post_by', models.CharField(default='admin', max_length=50)),
                ('views', models.IntegerField(default='0', editable=None)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, max_length=255, null=True, populate_from='title', unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.precosancategory')),
            ],
        ),
    ]
