# Generated by Django 4.1.1 on 2023-03-07 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_activitypost_category_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='pr_image',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.category'),
        ),
    ]
