# Generated by Django 4.1.1 on 2023-03-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_activitypost_post_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitypost',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
