# Generated by Django 4.1.1 on 2023-04-04 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_activitypost_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectMutipleActivityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='activity_post/')),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.activitypost')),
            ],
            options={
                'verbose_name_plural': 'Select Multiple Image',
            },
        ),
    ]
