# Generated by Django 4.1.1 on 2023-04-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_selectmutipleactivitypost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitypost',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
