# Generated by Django 4.1.1 on 2023-03-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurPublications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
                ('document', models.FileField(upload_to='pdf/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
