# Generated by Django 4.1.1 on 2023-03-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourpublications',
            options={'verbose_name_plural': 'Our Publication'},
        ),
        migrations.AddField(
            model_name='ourpublications',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='our_publications/image/'),
        ),
        migrations.AlterField(
            model_name='ourpublications',
            name='document',
            field=models.FileField(upload_to='our_publications/pdf/'),
        ),
    ]
