# Generated by Django 4.1.1 on 2023-03-16 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_publications', '0002_alter_ourpublications_options_ourpublications_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourpublications',
            name='document_status',
            field=models.SmallIntegerField(choices=[(1, 'Enable'), (0, 'Disable')], default=1),
        ),
        migrations.AddField(
            model_name='ourpublications',
            name='document_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourpublications',
            name='document_url_status',
            field=models.SmallIntegerField(choices=[(1, 'Enable'), (0, 'Disable')], default=1),
        ),
    ]
