# Generated by Django 4.1.1 on 2023-03-16 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_publications', '0003_ourpublications_document_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourpublications',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='our_publications/pdf/'),
        ),
    ]
