# Generated by Django 4.1.1 on 2023-02-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='https://statics.hemophilialucknow.org/images/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
