# Generated by Django 4.1.1 on 2023-02-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
