# Generated by Django 4.1.1 on 2023-02-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gallery_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image_url',
            field=models.URLField(blank=True, editable=False, null=True),
        ),
    ]
