# Generated by Django 4.1.1 on 2023-03-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_gallery_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='gallery/'),
        ),
    ]
