# Generated by Django 4.1.1 on 2023-01-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('contact1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact')),
                ('contact2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Alternate Contact')),
                ('email1', models.CharField(blank=True, max_length=40, null=True, verbose_name='Email')),
                ('email2', models.CharField(blank=True, max_length=40, null=True, verbose_name='Alternate Email')),
                ('on_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SiteName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_heading', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='site_image/')),
                ('site_desc', models.CharField(blank=True, max_length=500, null=True)),
                ('on_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(blank=True, max_length=250, null=True)),
                ('instagram', models.CharField(blank=True, max_length=250, null=True)),
                ('youtube', models.CharField(blank=True, max_length=250, null=True)),
                ('twitter', models.CharField(blank=True, max_length=250, null=True)),
                ('on_date', models.DateTimeField()),
            ],
        ),
    ]
