# Generated by Django 4.1.1 on 2023-01-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caption', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='on_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sitename',
            name='on_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='on_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
