# Generated by Django 4.1.1 on 2023-01-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caption', '0002_alter_contactus_on_date_alter_sitename_on_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='edit',
            field=models.CharField(blank=True, default='Edit', editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitename',
            name='edit',
            field=models.CharField(blank=True, default='Edit', editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='social',
            name='edit',
            field=models.CharField(blank=True, default='Edit', editable=False, max_length=50, null=True),
        ),
    ]
