# Generated by Django 4.1.1 on 2023-01-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caption', '0003_contactus_edit_sitename_edit_social_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='facebook_group',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
