# Generated by Django 4.1.1 on 2023-03-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='aadhar_image',
            field=models.ImageField(blank=True, null=True, upload_to='contact/'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='address',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
