# Generated by Django 4.1.1 on 2023-02-24 08:47

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutHemophilia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit', models.CharField(blank=True, default='Edit', editable=False, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hemophilia/')),
                ('english', tinymce.models.HTMLField(blank=True, null=True)),
                ('hindi', tinymce.models.HTMLField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('father_name', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('aadhar_no', models.CharField(blank=True, max_length=12, null=True)),
                ('mobile', models.BigIntegerField()),
                ('whatsapp_no', models.BigIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('comment', models.TextField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='doctorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryHemophilia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit', models.CharField(blank=True, default='Edit', editable=False, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hemophilia/')),
                ('english', tinymce.models.HTMLField(blank=True, null=True)),
                ('hindi', tinymce.models.HTMLField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocietyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='co-member/')),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Enable'), (0, 'Disable')], default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_title', models.CharField(max_length=255)),
                ('youtube_link', embed_video.fields.EmbedVideoField()),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='youtube_title', unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('mobile', models.CharField(max_length=10, null=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doctorcategory')),
            ],
        ),
    ]
