# Generated by Django 4.1.1 on 2023-02-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_img', models.ImageField(null=True, upload_to='banner/')),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_heading', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('link_text', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Enable'), (0, 'Disable')], default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
