# Generated by Django 4.1.1 on 2023-01-19 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OurTeam',
        ),
    ]
