# Generated by Django 4.1.1 on 2023-02-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contactus',
        ),
        migrations.AlterModelOptions(
            name='abouthemophilia',
            options={'verbose_name_plural': 'About Hemophilia'},
        ),
        migrations.AlterModelOptions(
            name='doctorcategory',
            options={'verbose_name_plural': 'doctor Category'},
        ),
        migrations.AlterModelOptions(
            name='historyhemophilia',
            options={'verbose_name_plural': 'History Hemophilia'},
        ),
        migrations.AlterModelOptions(
            name='societymember',
            options={'verbose_name_plural': 'Society Member'},
        ),
        migrations.AlterField(
            model_name='societymember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='society-member/'),
        ),
    ]
