# Generated by Django 4.1.1 on 2023-01-21 10:48

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_abouthemophilia'),
    ]

    operations = [
        migrations.AddField(
            model_name='abouthemophilia',
            name='edit',
            field=models.CharField(blank=True, default='Edit', editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='abouthemophilia',
            name='hindi',
            field=tinymce.models.HTMLField(blank=True, default='None', null=True),
        ),
    ]
