# Generated by Django 4.1.1 on 2023-03-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_contactus_alter_abouthemophilia_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societymember',
            name='image',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='society-member/'),
        ),
    ]
