# Generated by Django 4.1.1 on 2023-04-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_societymember_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='societymember',
            options={'ordering': ['my_order']},
        ),
        migrations.AddField(
            model_name='societymember',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='mobile',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='societymember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='society-member/'),
        ),
    ]
