# Generated by Django 4.1.1 on 2023-01-21 10:49

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_abouthemophilia_edit_alter_abouthemophilia_hindi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouthemophilia',
            name='hindi',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
