# Generated by Django 4.1.1 on 2023-02-01 19:44

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_abouthemophilia_hindi'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryHemophilia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit', models.CharField(blank=True, default='Edit', editable=False, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hemophilia/')),
                ('english', tinymce.models.HTMLField(blank=True, null=True)),
                ('hindi', tinymce.models.HTMLField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
