# Generated by Django 4.1.1 on 2023-04-02 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_societymember_options_societymember_my_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='societymember',
            options={'verbose_name_plural': 'Society Member'},
        ),
        migrations.RemoveField(
            model_name='societymember',
            name='my_order',
        ),
    ]
